[project]
name = "hxb-mcp-demo"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "侯晓宝", email = "xiaobaoword@163.com" }
]
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.10.1",
]

[project.scripts]
hxb-mcp-demo = "hxb_mcp_demo:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
