[project]
name = "jsonstruct-cli"
version = "0.1.19"
description = "Format deeply nested JSON and decode JWTs"
readme = "README.md"
requires-python = ">=3.7"
dependencies = ["pyjwt"]

[project.scripts]
jsonstruct = "jsonstruct.cli:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["jsonstruct"]
