[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "dj_palette"
version = "0.0.2.1"
authors = [
  { name="Joel O. Tanko", email="7thogofe@gmail.com" },
]
description = "A django admin system with tools for building custom admin interfaces and reuseable components"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/ogofe/django-palette"
Issues = "https://github.com/ogofe/django-palette/issues"