[project]
name = "azt-mcp-server"
version = "0.1.4"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "build>=1.2.2.post1",
    "httpx>=0.28.1",
    "mcp[cli]>=1.10.1",
    "requests>=2.32.4",
    "twine>=6.1.0",
]

[tool.uv.workspace]
members = ["venv"]

[project.scripts]
azt-mcp-server = "open_mcp.mcp_server_ypt:main"
