debugMode: false
logLevel: INFO
prettyPrintLogs: true
configPath: /etc/fastloop.d/
loopDelayS: 0.1
ssePollIntervalS: 0.1
sseKeepAliveS: 10.0
state:
  type: redis
  redis:
    host: "localhost"
    port: 6379
    database: 0
    password: ""
    ssl: false
  s3:
    aws_access_key_id: ""
    aws_secret_access_key: ""
    region_name: "us-east-1"
    bucket_name: "fastloop"
    prefix: "fastloop"