[project]
name = "query-farm-sql-scan-planning"
version = "0.1.4"
description = "A Python library for intelligent file filtering using SQL expressions and metadata-based scan planning. This library enables efficient data lake query optimization by determining which files need to be scanned based on their statistical metadata."
authors = [
    { name = "Rusty Conover", email = "rusty@conover.me" }
]
dependencies = [
    "sqlglot>=26.33.0",
    "duckdb>=1.3.2",
    "pyarrow>=20.0.0",
]
readme = "README.md"
requires-python = ">= 3.11"
keywords = ["sql", "predicate pushdown", "sql scan planning", "scan planning"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Database",
    "Topic :: Database :: Database Engines/Servers",
    "Programming Language :: Python :: 3.11"
]



[project.urls]
Repository = "https://github.com/query-farm/python-sql-scan-planning.git"
Issues = "https://github.com/query-farm/python-sql-scan-planning/issues"

[build-system]
requires = ["hatchling==1.26.3", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.3.2",
    "pytest-mypy>=0.10.3",
    "pytest-env>=1.1.3",
    "pytest-cov>=5.0.0",
    "ruff>=0.6.2",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/query_farm_sql_scan_planning"]
