[tool.poetry]
name = "ufcpredictor"
readme = "README.md"
version = "1.2.0"
description = "A simple predictor for UFC fights"
authors = ["César Ramírez-Pérez"]

[tool.poetry.dependencies]
python = ">=3.10,<4"
fuzzywuzzy = "^0.18.0"
huggingface-hub = "^0.26.2"
gradio = "^5.6.0"
matplotlib = "^3.9.2"
mlflow = "^2.18.0"
numpy = "^2.1.3"
pandas = "^2.2.3"
scikit-learn = "^1.5.2"
torch = "^2.5.1"
tqdm = "^4.67.0"
ufcscraper = "^0.2.0"

[tool.poetry.group.dev.dependencies]
python-semantic-release = "^9.14.0"
coverage = "^7.9.1"

[tool.semantic_release]
version_toml = [
    "pyproject.toml:tool.poetry.version",
]  
branch = "main"
changelog_file = "CHANGELOG.md"
build_command = "pip install poetry && poetry build"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ufcpredictor_app = "ufcpredictor.app:main"
