
[build-system]
requires = [ "hatchling" ]
build-backend = "hatchling.build"

[project]
name = "vovk_hello_world"
version = "0.0.5"
description = "A showcase for Next.js + Vovk.ts + Zod, demonstrating its capabilities with TypeScript, Rust, and Python RPC."
requires-python = ">=3.7"
authors = [ ]
dependencies = [ "requests", "jsonschema", "rfc3987", "urllib3==1.26.15" ]

  [project.license]
  text = "MIT"

  [project.optional-dependencies]
  dev = [ "types-requests", "types-jsonschema" ]


