[project]
name = "sailMate"
version = "0.0.2"
authors = [
  { name="Marina M", email="marinamolina7877@gmail.com" },
]
description = "A really bad chess engine that served as a learning project"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/marinamolinat/Sailmate-a-chess-engine"
