[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pim-cli"
version = "0.2.1"
description = "A pip-inspired CLI tool for managing ML models via a Pimfile"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
  {name = "Maxim Mounier", email = "maximmounier02@gmail.com"},
]
dependencies = [
  "pyyaml"
]

[project.scripts]
pim = "pim.cli:main"
