name: CICD PyPI

on:
  push:
    # use: git tag v0.1.0 && git push origin --tags
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up venv
        run: uv venv --python 3.12

      - name: Install dependencies
        run: uv sync && rm -rf uv.lock

      - name: Run tests
        run: uv run pytest --cov=src/

      - name: Build package
        run: uv build

      - name: Publish package
        run: uv publish -t ${{ secrets.PYPI_TOKEN }}

      - name: Create GitHub Release
        run: |
          python -m pip install -q setuptools_scm
          VERSION=$(python -c 'from setuptools_scm import get_version; print(get_version())')
          gh release create "v${VERSION}" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}