[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "open_corpus_co_es"
version = "0.1.1a2"
description = "Corpus en espaÃ±ol de Colombia para procesamiento de lenguaje natural"
authors = [
    {name = "Luis Gabriel Moreno Sandoval", email = "morenoluis@javeriana.edu.co"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.6"
dependencies = ["nltk", "pandas", "gdown", "pyarrow", "fastparquet", "tqdm"]

[tool.setuptools]
packages = ["open_corpus_co_es"]
include-package-data = true
