[project]
name = "tumblrbot"
version = "1.4.5"
description = "An updated bot that posts to Tumblr, based on your very own blog!"
readme = "README.md"
requires-python = ">= 3.13"
dependencies = [
  "httpx[http2]",
  "keyring",
  "more-itertools",
  "niquests[speedups,http3]",
  "openai",
  "pwinput",
  "pydantic",
  "pydantic-settings",
  "requests-oauthlib",
  "rich",
  "tiktoken",
  "tomlkit",
]

[project.urls]
Source = "https://github.com/MaidThatPrograms/tumblrbot"

[project.scripts]
tumblrbot = "tumblrbot.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
