[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "magic-tools"
version = "0.1.3"
authors = [
  { name="Muieay", email="muieay@example.com" },
]
description = "Python daily widgets"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = {file = "LICENSE"}

[project.urls]
"Homepage" = "https://github.com/muieay/magic-tools"
"Bug Tracker" = "https://github.com/muieay/magic-tools/issues"
