[project]
name = "mcp-server-vecx"
version = "0.1.4"
description = "VectorX Mcp Server"
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
dependencies = [
    "fastmcp>=2.10.4",
    "vecx>=0.33.1"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
mcp-server-vecx = "mcp_server_vecx.main:main"

