[project]
name = "dearpygui-forms"
version = "0.2.1"
description = "Dearpygui extention for autogeneration forms powered by pydantic."
readme = "README.md"
authors = [
    { name = "Valentin Lewicki", email = "vlewicki@vlewicki.ru" }
]
requires-python = ">=3.10"
dependencies = [
    "dearpygui>=2.0.0",
    "loguru>=0.7.3",
    "pydantic>=2.11.7",
]

[project.urls]
homepage = "https://github.com/vlewicki/dearpygui-forms"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pylint>=3.3.7",
]
