[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vane-native"
version = "0.1.0a1"
description = "Modular colourised logger with pluggable backends (TBD)"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [{ name = "Jakub GÃ³rski", email = "kuba.gorsky@gmail.com" }]
dependencies = [
  "colorama>=0.4.6"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.optional-dependencies]
dev = [
  "pytest>=8.0",
  "pytest-cov",
  "build",
  "twine"
]