[project]
name = "strongbus"
version = "0.1.1"
description = "A type-safe event bus library for Python that provides reliable publish-subscribe messaging with automatic memory management and full type safety."
readme = "README.md"
authors = [{ name = "Marius RÃ¤sener", email = "marius@raesener.de" }]
requires-python = ">=3.10"
dependencies = []
keywords = ["events", "event-bus", "typed", "type-safe", "pubsub"]

[project.urls]
Repository = "https://github.com/elmcrest/strongbus"

[project.optional-dependencies]
dev = ["tox", "build", "pytest-cov>=6.2.1"]

[project.scripts]
strongbus = "strongbus:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
