[project]
name = "dpod"
version = "0.1.13"
description = "CLI для взаимодействия с Dispersion Platform"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx",
    "questionary",
    "rich",
    "click",
    "uv",
    "archtool",
    "web_fractal",
    "fastapi",
    "sqlalchemy",
    "aiohttp",
    "furl",
    "docker",
    "harborapi",
    "zmq",
    "pytz"
]

[project.scripts]
dp = "dpod.entrypoints.commander:cli"

