[project]
name = "concat-stories"
version = "0.4.0"
description = "Concatenate Snapchat stories."
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Ayoub Dya", email = "ayoubdya@gmail.com" }]
keywords = ["concat-stories", "snapchat", "stories", "video", "concatenate"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
]
dependencies = ["loguru", "requests", "ffmpeg-python"]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/ayoubdya/concat-stories"

[project.scripts]
concat-stories = "concat_stories.app:main"

[dependency-groups]
dev = ["ruff>=0.12.2"]

[tool.ruff]
indent-width = 2
