[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "swapi-client"
version = "0.2.2"
description = "API client for Serwis Planner"
readme = "README.md"
requires-python = ">=3.12"
license = { file = "LICENSE" }
authors = [
    { name = "qwizi", email = "qwizi@qwizi.dev" },
]
dependencies = [
    "httpx>=0.27.0",
    "python-dotenv>=1.0.1",
]

[project.urls]
Homepage = "https://github.com/qwizi/swapi-client"
"Bug Tracker" = "https://github.com/qwizi/swapi-client/issues"
