[tool.poetry]
name = "fluidattacks-core"
version = "2.8.2"
description = "Fluid Attacks Core Library"
authors = ["Development <development@fluidattacks.com>"]
license = "MPL-2.0"
readme = "README.md"
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries",
]

[tool.poetry.dependencies]
python = "^3.11"
aiofiles = ">=23.2.1"
aiohttp = ">=3.10.0"
boto3 = ">=1.34"
bugsnag = ">=4.7.1"
certifi = ">=2024.8.30"
GitPython = ">=3.1.41"
pathspec = ">=0.12.1"
urllib3 = ">=2.2.3"
tree-sitter = "0.24.0"
more-itertools = "^10.0.0"
tree-sitter-c-sharp = "^0.23.1"
tree-sitter-go = "^0.23.4"
tree-sitter-java = "^0.23.4"
tree-sitter-javascript = "^0.23.1"
tree-sitter-json = "^0.24.8"
tree-sitter-kotlin = "^1.0.1"
tree-sitter-python = "^0.23.4"
tree-sitter-php = "^0.23.11"
tree-sitter-typescript = "^0.23.2"
tree-sitter-yaml = "^0.7.0"
tree-sitter-html = "^0.23.2"
tree-sitter-xml = "^0.7.0"

[tool.poetry.group.dev.dependencies]
boto3-stubs = { extras = [
    "essential",
    "dynamodbstreams",
    "sts",
], version = ">=1.34.0" }
botocore-stubs = "1.35.71"
import-linter = "2.1"
mypy = "1.13.0"
ruff = "0.8.0"
types-aiofiles = "24.1.0.20240626"
pytest = "8.3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
