[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"   

[project]
name = "clip_protocol"
version = "2.2.13"
authors = [
  { name="Marta Jones GonzÃ¡lez", email="martajon10@gmail.com" },
]
description = "Protocol to ensure the privatization of "
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "matplotlib",
    "numpy",
    "pandas",
    "progress",
    "tabulate",
    "sympy",
    "scipy",
    "tqdm",
    "optuna",
    "openpyxl",
    "rich",
    "colorama",
    "numba",
    "appdirs"
]

[project.urls]
Homepage = "https://github.com/martaajonees/Local_Privacy"
Issues = "https://github.com/martaajonees/Local_Privacy/issues"

[project.scripts]
setup = "clip_protocol.cli:cli_setup"
mask = "clip_protocol.cli:cli_mask"
aggregate = "clip_protocol.cli:cli_agregate"
estimate = "clip_protocol.cli:cli_estimate"
clip_clear = "clip_protocol.cli:clear"

[tool.setuptools]
include-package-data = true


