[tool.poetry]
name = "whitebox-plugin-device-manager"
version = "0.1.2"
description = "A plugin for whitebox to manage devices"
authors = ["Milos <hello@klined.org>", "avilabss <contact@avilabs.net>", "WhiteBox <contact@whitebox.aero>"]
license = "GNU Affero General Public License v3"
readme = "README.md"
include = [
    { path = "whitebox_test_plugin_device_manager", format = "wheel" }
]

[tool.poetry.dependencies]
python = ">=3.10.0"


[tool.poetry.group.dev.dependencies]
ruff = "^0.6.5"
coverage = "^7.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
