
[project]
name = "jusflaudio"
version = "0.1.5"
description = "Useful audio tools"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argostranslate>=1.9.6",
    "autocorrect>=2.6.1",
    "click>=8.2.1",
    "console>=0.9911",
    "faster-whisper>=1.1.1",
    "pysubs2>=1.8.0",
    "requests>=2.32.4",
    "srt>=3.5.3",
]

[project.scripts]
jusflaudio = "jusflaudio:main"
fawhis = "jusflaudio.fawhis:main"
mpvsa = "jusflaudio.mpvsa:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
