[project]
name = "jbussdieker"
version = "0.15.1"
description = "A modern Python development toolkit."
readme = "README.md"
requires-python = ">=3.9"
dependencies = []
authors = [
  { name = "Joshua B. Bussdieker", email = "jbussdieker@gmail.com" }
]
maintainers = [
  { name = "Joshua B. Bussdieker", email = "jbussdieker@gmail.com" }
]
classifiers = [
  "Topic :: Software Development :: Build Tools",
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Operating System :: OS Independent",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Natural Language :: English",
  "Typing :: Typed",
]
license = "MIT"
license-files = ["LICENSE"]

[project.optional-dependencies]
ai = [
    "openai>=1.0.0",
]

[project.scripts]
jbussdieker = "jbussdieker.cli:main"

[project.urls]
Homepage = "https://github.com/jbussdieker/python-jbussdieker"
Documentation = "https://github.com/jbussdieker/python-jbussdieker/blob/main/README.md"
Repository = "https://github.com/jbussdieker/python-jbussdieker"
Issues = "https://github.com/jbussdieker/python-jbussdieker/issues"
Changelog = "https://github.com/jbussdieker/python-jbussdieker/blob/main/CHANGELOG.md"

[tool.setuptools.package-data]
jbussdieker = ["templates/.*.tpl", "templates/*.tpl"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
