[project]
name = "pymlt"
dynamic = ["version"]
description = "Python Machine Learning Toolkit"
authors = [
    { name = "Ben van Vliet", email = "benvliet@icloud.com" }
]
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
dependencies = [
    "pytest",
    "pytest-cov",
    "setuptools-scm",
]

[build-system]
requires = ["setuptools>=64", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# version_scheme = "post-release"
# local_scheme = "no-local-version"