[project]
name = "vdsnow"
version = "0.5.3"
authors = [
  { name="Vitor Duarte", email="vitordduarte95@gmail.com" },
]
description = "A CLI for Snowflake project scaffolding, execution, and validation."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "click>=8.1.8",
    "pyfiglet>=1.0.3",
    "pytest>=8.4.1",
    "rich>=14.0.0",
    "snowflake-cli>=3.9.1",
    "tomli>=2.2.1",
    "tomli-w>=1.2.0",
]

[project.scripts]
vdsnow = "vdsnow.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
