[tool.poetry]
name = "explainiverse"
version = "0.1.1a0"
description = "Unified, extensible explainability framework supporting LIME, SHAP, and custom adapters"
authors = ["Muntaser Syed <jemsbhai@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jemsbhai/explainiverse"
homepage = "https://github.com/jemsbhai/explainiverse"
packages = [{ include = "explainiverse", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = "1.24.4"
lime = "^0.2.0.1"
scikit-learn = ">=1.1,<1.4"
shap = "^0.48.0"
xgboost = "^3.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project.urls]
"Bug Tracker" = "https://github.com/jemsbhai/explainiverse/issues"
"Documentation" = "https://github.com/jemsbhai/explainiverse#readme"