[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "unichat"
version = "4.1.17"
authors = [
    { name = "Stefan", email = "versed_info0w@icloud.com" },
]
description = "Universal API chat Python client for OpenAI, MistralAI, Anthropic, xAI, Google AI, DeepSeek, Alibaba and Inception"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
dependencies = [
    "anthropic~=0.54.0",
    "mistralai~=1.8.2",
    "openai~=1.86.0",
]

[project.urls]
Repository = "https://github.com/amidabuddha/unichat"