[project]
name = "seeder-py"
version = "0.1.1"
description = "A Python library for data seeding, making data preparation for integration testing easier."
readme = "README.md"
authors = [
    { name = "chehsunliu", email = "chehsunliu@gmail.com" }
]
license-files = ["./LICENSE"]

requires-python = ">=3.10"
dependencies = []

[project.urls]
Homepage = "https://github.com/chehsunliu/seeder.py"
Repository = "https://github.com/chehsunliu/seeder.py.git"
Issues = "https://github.com/chehsunliu/seeder.py/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/seeder"]

[dependency-groups]
dev = [
    "boto3-stubs[s3]>=1.39.4",
    "pytest>=8.4.1",
    "pytest-datadir>=1.7.2",
    "pytest-mock>=3.14.1",
    "ruff>=0.12.3",
]
minio = [
    "boto3>=1.39.4",
]
redis = [
    "redis[hiredis]>=6.2.0",
]

[tool.ruff]
line-length = 120
