[project]
name = "rstt"
version = "0.6.6.1"
description = "Ranking Simulation Testing Tool"
authors = [
    {name = "Bucher David", email = "davidbucherdev@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "typeguard (>=3.0.0,<3.0.2)",
    "numpy (>=2.2.2,<3.0.0)",
    "names (>=0.3.0,<0.4.0)",
]
classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Science/Research',
    'Topic :: Scientific/Engineering',
    'Topic :: Games/Entertainment',
    'Topic :: Games/Entertainment :: Simulation',
    'Typing :: Typed',
]


[project.urls]
repository = "https://github.com/Ematrion/rstt"
documentation = "https://rstt.readthedocs.io/en/latest/"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

