[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "sskw-tasks"
version = "0.4.2"
authors = [
    {name="liwei", email="491520313@qq.com"},
]
description = "sskw shared celery task declaration"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
dependencies = [
    "celery>=5.5.3",
    "pydantic>=2.10.6",
]

[project.urls]
Homepage = "https://tasks.sensearray.com/docs"

[dependency-groups]
dev = [
    "build>=1.2.2.post1",
    "twine>=6.1.0",
]

[tool.uv]
index-url = "https://mirrors.aliyun.com/pypi/simple/"