[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agentix-notifications"
version = "0.0.2"
description = "Notifications plugin for Agentix platform (WhatsApp, Email)"
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
  "aiohttp>=3.8.0",
  "requests"
]

[project.optional-dependencies]
dev = [
  "agentix-core"
]

[project.urls]
"Homepage" = "https://github.com/FIDOX/py-plugin-agentix-notifications"
"Bug Tracker" = "https://github.com/FIDOX/py-plugin-agentix-notifications/issues"

[tool.setuptools.packages.find]
where = ["src"]