[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "izsdk"
version = "1.0.4"
description = "Ysafe SDK for interacting with the Ysafe API"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
dependencies = [
    "beautifulsoup4>=4.13.4",
    "cachetools>=6.1.0",
    "google>=3.0.0",
    "iniconfig>=2.1.0",
    "packaging>=25.0",
    "pluggy>=1.6.0",
    "protobuf>=6.31.1",
    "Pygments>=2.19.2",
    "asyncio>=1.0.0",
    "soupsieve>=2.7",
    "typing_extensions>=4.14.0",
    "websockets>=15.0.1",
]

[project.urls]
Homepage = "https://github.com/Induzio/iz-python"
