[project]
name = "gemini-cli-mcp"
version = "0.1.4"
description = "Gemini CLI MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.0",
    "mcp[cli]>=1.10.1",
    "pytest>=8.4.1",
    "python-dotenv>=1.1.1",
    "uv>=0.7.20",
    "uvicorn>=0.35.0",
]

[project.scripts]
gemini-cli-mcp = "main:main"

[tool.setuptools]
py-modules = ["main"]
