[project]
name = "lightudq"
version = "0.1.2"
description = "assess unstructured data quality"
readme = "README.md"
authors = [
    { name = "Sarabjot Singh", email = "sarabjot@lightup.ai" }
]
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "pdoc>=15.0.4",
    "pre-commit>=4.2.0",
    "pydantic>=2.11.5",
    "pydantic-ai>=0.2.16",
    "pymupdf>=1.26.0",
    "pytest>=8.4.0",
    "twine>=6.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "build>=1.2.2.post1",
    "twine>=6.1.0",
]

[project.urls]
Homepage = "https://github.com/lightup-data/lightudq"
Repository = "https://github.com/lightup-data/lightudq"
Documentation = "https://github.com/lightup-data/lightudq#readme"
"Issue Tracker" = "https://github.com/lightup-data/lightudq/issues"
