[project]
name = "pygame-brickbreaker"
version = "1.0.2"
description = "ğŸ® A classic brick breaker game built with Python and Pygame."
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}
authors = [{name = "Priyanshu Raj", email = "prmahatha@gmail.com"}]
dependencies = ["pygame"]

[project.scripts]
brickbreaker = "pygame_brickbreaker.game:main"

[tool.setuptools]
include-package-data = true

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
