[project]
name = "sdbtool"
version = "0.4.5"
description = "Dump SDB file to xml using apphelp.dll"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Mark Jansen", email = "mark.jansen@reactos.org" }
]
requires-python = ">=3.10"
dependencies = [
    "click>=8.2.1",
]
keywords = ["sdb", "sdbtool", "sdb2xml", "shim", "apphelp", "appcompat", "shimeng"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Programming Language :: Python :: 3",
    "Operating System :: Microsoft :: Windows",
    "Topic :: Utilities",
]

[project.urls]
Homepage = "https://pypi.org/project/sdbtool/"
Changelog = "https://github.com/learn-more/sdbtool/releases"
Issues = "https://github.com/learn-more/sdbtool/issues"
CI = "https://github.com/learn-more/sdbtool/actions"
Repository = "https://github.com/learn-more/sdbtool"

[project.scripts]
sdbtool = "sdbtool.cli:sdbtool_command"
sdb2xml = "sdbtool.cli:sdb2xml_command"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
exclude = [
  ".vscode",
  ".python-version",
  "uv.lock",
  "tests"
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]

