# mf4_processor_package/pyproject.toml

[build-system]
requires = ["setuptools>=61.0"] 
build-backend = "setuptools.build_meta"

[project]
name = "rosbag2_mf4_preprocessing_tools" 
version = "0.4.29" 
authors = [
  { name="Bora", email="bbpilav@gmail.com" }, 
]
description = "Tools for preprocessing MF4 and Rosbag files in an Airflow DAG."
readme = "README.md" 
requires-python = ">=3.8" 
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License", 
    "Operating System :: OS Independent",
]

dependencies = [
    "numpy",
    "tables",
    "asammdf",
    "pandas",
    "pyyaml",
]

[project.urls] 
"Homepage" = "https://github.com/yourusername/mf4_processor_package" 
"Bug Tracker" = "https://github.com/yourusername/mf4_processor_package/issues"

[tool.setuptools.packages.find]
where = ["src"]  