[project]
name = "awesome-structure"
version = "0.1.1"
description = "Ð’ÑÐµÐ³Ð¾ Ð¾Ð´Ð½Ð° ÐºÐ¾Ð¼Ð°Ð½Ð´Ð° Ð² Ñ‚ÐµÑ€Ð¼Ð¸Ð½Ð°Ð»Ðµ, Ð¾Ñ‚Ð´ÐµÐ»ÑÑŽÑ‰Ð°Ñ Ð²Ð°Ñ Ð¾Ñ‚ Ð½Ð°ÑÐ»Ð°Ð¶Ð´ÐµÐ½Ð¸Ñ Ð¿Ñ€ÐµÐºÑ€Ð°ÑÐ½Ð¾Ð¹ ÑÑ‚Ñ€ÑƒÐºÑ‚ÑƒÑ€Ð¾Ð¹ Ð²Ð°ÑˆÐµÐ³Ð¾ Ð¿Ñ€Ð¾ÐµÐºÑ‚Ð° ðŸ˜Œ"
authors = [
    {name = "Dmitry-Peskov",email = "dv.peskov@yandex.ru"}
]
readme = "README.md"
homepage = "https://gitverse.ru/dv.peskov/awesome-structure"
repository = "https://gitverse.ru/dv.peskov/awesome-structure"
keywords = ["cli", "directory", "tree", "visualization"]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
]

[tool.poetry]
packages = [{include = "awesome_structure", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.7"

[tool.poetry.group.test.dependencies]
pytest = "^8.4.1"
pytest-cov = "^6.2.1"
pytest-mock = "^3.14.1"

[poetry.group.dev.dependencies]
ruff = "^0.1.0"
black = "^23.10.0"
isort = "^5.12.0"

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["awesome_structure"]

[tool.ruff]
line-length = 88
select = ["E", "F", "W", "I", "B", "C90"]
ignore = ["E501"]

[tool.black]
line-length = 88
target-version = ['py310']

[tool.pytest.ini_options]
testpaths = "tests"
python_files = "test_*.py"
python_functions = "test_*"
addopts = "--cov=src --cov-report=term-missing"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
awesome-structure = "awesome_structure.cli:cli"
