[project]
name = "R-AScan"
version = "0.0.13"
description = "Rusher Automatic Scan"
authors = [
  { name="HarshXor", email="harshxor@incrustwerush.org" }
]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
  "requests>=2.25.1",
  "colorama>=0.4.6",
  "beautifulsoup4>=4.12.3",
  "pandas>=1.3.5",
  "scikit-learn>=1.1.3",
  "numpy>=1.21.0"
]

[project.scripts]
R-AScan = "r_ascan.app:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"r_ascan.resources" = ["*.*"]
"r_ascan.module" = ["*.*"]
"r_ascan.scanners" = ["*.*"]
