[project]
name = "gitify"
version = "0.0.1"
description = "Automatically generate Github commit messages and readme files using LLMs."
authors = [{ name = "Josh Pearlson", email = "jcpearlson@gmail.com" }]
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

