[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dockwatch"
version = "1.00"
description = "ðŸ›¡ï¸  DockWatch - Docker container monitoring and image analysis cli tool."
authors = [{ name = "Saimon Bhuiyan", email = "bsse1402@iit.du.ac.bd" }]
readme = "README.md"
requires-python = ">=3.7"
dependencies = ["docker", "rich"]

[project.scripts]
dockwatch = "dockwatch.cli:main"
