[project]
name = "bfg-llmutil"
version = "0.5.4"
description = "A set of utility functions to handle LLM structural output"
readme = "README.md"
authors = [
    { name = "leizha", email = "8961794+leizha@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = ["openai", "bfg-schemautil"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/llmutil"]
