[tool.poetry]
name = "laff"
version = "0.13.10"
description = "GRB lightcurve flare and continuum fitter."
authors = ["Adam Hennessy <ah724@leicester.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9, <3.13"
pandas = "^2.0.1"
matplotlib = "^3.7.1"
numpy = "^1.24.3"
scipy = "^1.10.1"
astropy = "^5.2.2"
bottleneck = "^1.3.8"


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
notebook = "^7.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
