[project]
name = "mcp-zhysfl"
version = "0.4.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "graphrag>=2.3.0",
    "mcp>=1.10.1",
    "openai>=1.93.2",
    "python-dotenv>=1.1.1",
]
