[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lotuschat-bot-sdk"
version = "0.1.22"
description = "SDK for interacting with LotusChat API"
readme = "README.md"
authors = [{ name="Yuriko", email="tunguyenanh@vccorp.vn" }]
license = {text = "MIT"}
dependencies = ["requests", "schedule", "flask", "pydantic", "aiohttp", "quart", "asgiref"]

[project.urls]