[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "iLaplace"
version = "0.4.4"
description = "High-precision numerical inverse Laplace transform calculation library"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
authors = [
    { name = "Mohammad H. Rostami", email = "MHRo.R84@Gmail.com" }
]
keywords = ["inverse", "laplace", "transform", "numerical", "mathematics"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Intended Audience :: Science/Research"
]
dependencies = [
    "mpmath>=1.2.1",
    "sympy>=1.10",
    "numpy>=1.20",
    "matplotlib>=3.0"
]

[tool.setuptools.packages.find]
include = ["iLaplace", "iLaplace.*"]
