model_name: cnn
num_clients: 100
global_round: 5
sample_ratio: 1.0
partition: shards
num_shards: 200
dir_alpha: 1.0
seed: 42
epochs: 5
lr: 0.1
batch_size: 50
num_parallels: 10
dataset_root_dir: /tmp/quickstart-fedavg/dataset
dataset_split_dir: /tmp/quickstart-fedavg/split
share_dir: /tmp/quickstart-fedavg/share
state_dir: /tmp/quickstart-fedavg/state
execution_mode: multi-process
ipc_mode: shared_memory
