[project]
name = "query-farm-sql-manipulation"
version = "0.1.5"
description = "A Python library for intelligent SQL predicate manipulation using SQLGlot. This library provides tools to safely remove specific predicates from `SQL WHERE` clauses and filter SQL statements based on column availability."
authors = [
    { name = "Rusty Conover", email = "rusty@query.farm" }
]
dependencies = [
    "sqlglot>=26.33.0",
]
readme = "README.md"
requires-python = ">= 3.11"
keywords = ["sql", "predicates", "predicate parsing", "sql parsing"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Database",
    "Topic :: Database :: Database Engines/Servers",
    "Programming Language :: Python :: 3.11"
]

[project.urls]
Repository = "https://github.com/query-farm/python-sql-manipulation.git"
Issues = "https://github.com/query-farm/python-sql-manipulation/issues"


[build-system]
requires = ["hatchling==1.26.3", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.4.1",
    "mypy>=1.16.1",
    "lxml>=6.0.0",
    "pytest-mypy>=0.10.3",
    "pytest-env>=1.1.3",
    "pytest-cov>=5.0.0",
    "ruff>=0.6.2",
]

[tool.rye.include]
files = ["py.typed"]


[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/query_farm_sql_manipulation"]


[tool.pytest]

[tool.pytest.ini_options]


[tool.mypy]
ignore_missing_imports = true


follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true

# for strict mypy: (this is the tricky one :-))
disallow_untyped_defs = true


[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = ['E501']
