[project]
name = "create-rag-app"
version = "0.1.2"
description = "A command-line tool to generate modern RAG applications with various components."
authors = [
    {name = "Syed-MuhammadTaha",email = "simam.bscs22seecs@seecs.edu.pk"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "typer (>=0.16.0,<0.17.0)",
    "jinja2 (>=3.1.6,<4.0.0)",
    "questionary (>=2.1.0,<3.0.0)"
]

[project.urls]
"Homepage" = "https://github.com/Syed-MuhammadTaha/create-rag-app"
"Repository" = "https://github.com/Syed-MuhammadTaha/create-rag-app"

[tool.poetry]
packages = [{include = "create_rag_app", from = "src"}]

[tool.poetry.scripts]
create-rag-app = "create_rag_app.cli:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
