[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ipagent"
version = "0.1.3"
description = "FastAPI dependency: get client IP, device, browser, and geo data"
authors = [{ name = "Musharraf Ibragimov" }]
license = { text = "MIT" }
readme = "README.md"
dependencies = [
    "fastapi",
    "httpx",
    "user-agents",
    "pydantic"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Framework :: FastAPI",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers"
]
dynamic = ["requires-python"]


[project.urls]
"Homepage" = "https://github.com/allncuz/ipagent"
"Issues" = "https://github.com/allncuz/ipagent/issues"
